[features]
seeds = false
skip-lint = false
[programs.localnet]
code_snippets = "GxK3JBJA7KbczThpSAsNnqJBRFrELEctieJWRyvYhkMV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/moviendome/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
